version: 1
send_anonymous_usage_stats: true
project_id: tap-facebook
plugins:
  extractors:
  - name: tap-facebook
    namespace: tap_facebook
    pip_url: -e .
    capabilities:
    - state
    - catalog
    - discover
    config:
      start_date: '2023-03-14T00:00:00Z'
      insights_buffer_days: 7
  - name: facebook-ads
    inherit_from: tap-facebook
    config:
      start_date: '2023-03-14T00:00:00Z'
    load_schema: TEST_MELTANO_FACEBOOK_STREAMS
    select:
    - ads.*
  - name: facebook-ads-insights
    inherit_from: tap-facebook
    config:
      start_date: '2023-03-14T00:00:00Z'
    select:
    - adsinsights.*
  - name: facebook-adsets
    inherit_from: tap-facebook
    config:
      start_date: '2023-03-14T00:00:00Z'
    select:
    - adsets.*
  - name: facebook-campaigns
    inherit_from: tap-facebook
    config:
      start_date: '2023-03-14T00:00:00Z'
    select:
    - campaigns.*
  loaders:
  - name: target-csv
    variant: hotgluexyz
    pip_url: git+https://github.com/hotgluexyz/target-csv.git@0.3.3
    config:
      destination_path: /home/xiao/Downloads/src/cerberus-netdiscover-flask/tap-facebook-sdk/output
  - name: target-snowflake
    variant: transferwise
    pip_url: pipelinewise-target-snowflake
    config:
      batch_size: 5
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
    config:
      destination_path: /home/xiao/Downloads/src/cerberus-netdiscover-flask/tap-facebook-sdk/output
      do_timestamp_file: true
      custom_name: meltano_sdk_output.json
