version: 1
environments:
- name: dev
send_anonymous_usage_stats: true
project_id: tap-facebook
plugins:
  extractors:
  - name: tap-facebook
    namespace: tap_facebook
    pip_url: -e .
    capabilities:
    - state
    - catalog
    - discover
    config:
      start_date: '2023-03-14T00:00:00Z'
      account_id: '542163415992887'
      insights_buffer_days: 7
      access_token: EAAxr7JKixwoBAAeby8W5wlE7gCoVJdwvry6ep8G5qDwLAikMrJrzNybuxWXKLaoD9JXfUYZAHMaZAELDv4QqEZAr7RMU6MLTy1EhtqZCljE7Q5EGon3wKIki90fVcGXRKzuc0TmJzziYSvHBZB8DZCMLxYEnpAVvgjIKPevMqIf1aLzRAUvkAI
  - name: facebook-ads
    inherit_from: tap-facebook
    config:
      start_date: '2023-03-14T00:00:00Z'
    load_schema: MELTANO_FACEBOOK
    select:
    - ads.*
  - name: facebook-ads-insights
    inherit_from: tap-facebook
    config:
      start_date: '2023-03-14T00:00:00Z'
    select:
    - adsinsights.*
  - name: facebook-adsets
    inherit_from: tap-facebook
    config:
      start_date: '2023-03-14T00:00:00Z'
    select:
    - adsets.*
  - name: facebook-campaigns
    inherit_from: tap-facebook
    config:
      start_date: '2023-03-14T00:00:00Z'
    select:
    - campaigns.*
  - name: facebook-adhistory
    inherit_from: tap-facebook
    config:
      start_date: '2023-03-14T00:00:00Z'
    select:
    - ad_history.*
  - name: facebook-campaignhistory
    inherit_from: tap-facebook
    config:
      start_date: '2023-03-14T00:00:00Z'
    select:
    - campaign_history.*
  - name: facebook-adsethistory
    inherit_from: tap-facebook
    config:
      start_date: '2023-03-14T00:00:00Z'
    select:
    - adset_history.*
  loaders:
  - name: target-csv
    variant: hotgluexyz
    pip_url: git+https://github.com/hotgluexyz/target-csv.git@0.3.3
    config:
      destination_path: /home/xiao/Downloads/src/cerberus-netdiscover-flask/tap-facebook-sdk/output
  - name: target-snowflake
    variant: transferwise
    pip_url: pipelinewise-target-snowflake
    config:
      batch_size: 5
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
    config:
      destination_path: /home/xiao/Downloads/src/cerberus-netdiscover-flask/tap-facebook-sdk/output
      do_timestamp_file: true
      custom_name: meltano_sdk_output.json
  transformers:
  - name: dbt-snowflake
    variant: dbt-labs
    pip_url: dbt-core~=1.3.0 dbt-snowflake~=1.3.0
    config:
      account: EPA06486
      user: RYAN_MIRANDA
      role: RYAN_MIRANDA
      warehouse: RYAN_MIRANDA
      database: RYAN_MIRANDA_RAW
      schema: MELTANO_FACEBOOK
