version: 1
default_environment: dev
send_anonymous_usage_stats: true
project_id: tap-facebook
plugins:
  extractors:
  - name: tap-facebook
    namespace: tap_facebook
    pip_url: -e .
    capabilities:
    - state
    - catalog
    - discover
    settings:
    - name: access_token
      kind: password
    - name: start_date
      value: '2023-03-01T00:00:00Z'
      kind: date_iso8601
    - name: end_date
      value: '2023-03-31T00:00:00Z'
      kind: date_iso8601
    - name: account_id
      kind: string
    - name: api_version
      value: 'v16.0'
    config:
      insights_buffer_days: 7
  loaders:
  - name: target-csv
    variant: hotgluexyz
    pip_url: git+https://github.com/hotgluexyz/target-csv.git@0.3.3
    config:
      destination_path: $MELTANO_OUTPUT_PATH
  - name: target-snowflake
    variant: transferwise
    pip_url: pipelinewise-target-snowflake
    config:
      batch_size: 5
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
    config:
      destination_path: $MELTANO_PROJECT_ROOT
      do_timestamp_file: true
      custom_name: $MELTANO_OUTPUT_FILE
environments:
    - name: dev
      config:
        plugins:
          loaders:
            - name: target-csv
            - name: target-snowflake
              config:
                default_target_schema: $TARGET_SNOWFLAKE_SCHEMA
                primary_key_required: false
    - name: staging
    - name: prod
